"""Add language to posts

Revision ID: 648350304e48
Revises: f7f72dce7903
Create Date: 2018-04-12 13:01:04.151174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '648350304e48'
down_revision = 'f7f72dce7903'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
